name: Build and Release macOS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, amd64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        OUTPUT="moeCounter-macos-${{ matrix.arch }}"
        GOOS=darwin GOARCH=${{ matrix.arch }} go build -o $OUTPUT ./main.go
        mv $OUTPUT macos-${{ matrix.arch }}
      continue-on-error: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.arch }}
        path: macos-${{ matrix.arch }}
        if-no-files-found: warn

  release:
    runs-on: ubuntu-latest
    needs: [build_macos]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: 'macos-*'

    - name: Compress binaries
      run: |
        cd artifacts
        for file in *; do
          if [ -f "$file" ]; then
            arch_name="${file#macos-}"
            zip -j "moeCounter-macos-${arch_name}.zip" "$file"
          fi
        done
        rm -rf *
        cd ..
      shell: bash

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: artifacts/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
