name: Build and Release Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64, arm64, 386]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        $output = "windows-${{ matrix.arch }}.exe"
        go build -o $output ./main.go
      continue-on-error: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-${{ matrix.arch }}
        path: windows-${{ matrix.arch }}.exe
        if-no-files-found: warn

  release:
    runs-on: ubuntu-latest
    needs: [build_windows]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: 'windows-*'

    - name: Compress binaries
      run: |
        cd artifacts
        for file in *; do
          if [ -f "$file" ]; then
            arch_name="${file#windows-}"
            arch_name="${arch_name%.exe}"  # 移除 .exe 扩展名
            zip -j "moeCounter-windows-${arch_name}.zip" "$file"
          fi
        done
        cd ..
      shell: bash

    - name: List artifacts
      run: |
        echo "Generated artifacts:"
        ls -l artifacts/ || true
      shell: bash

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: artifacts/moeCounter-windows-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up artifacts
      run: rm -rf artifacts
      shell: bash
