name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # 匹配语义化版本标签 (v1.0.0格式)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'  # 根据项目需要调整Go版本

    - name: Build
      run: |
        go build -o moeCounter ./main.go
        mkdir release
        mv moeCounter release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
