name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # 匹配语义化版本标签 (v1.0.0格式)

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
          # 排除不常见的组合
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        # 转换OS标识符为Go兼容格式
        case "${{ runner.os }}" in
          "Linux")
            GO_OS="linux"
            ;;
          "macOS")
            GO_OS="darwin"
            ;;
          "Windows")
            GO_OS="windows"
            ;;
          *)
            GO_OS="linux"
            ;;
        esac
        
        # 设置输出文件名
        OUTPUT="moeCounter-${{ runner.os }}-${{ matrix.arch }}"
        if [ "${{ runner.os }}" == "Windows" ]; then
          OUTPUT="$OUTPUT.exe"
        fi
        
        # 创建release目录（兼容Windows）
        mkdir -p release
        
        # 构建二进制到release目录
        GOOS=$GO_OS GOARCH=${{ matrix.arch }} go build -o release/$OUTPUT ./main.go
      # 添加错误继续选项
      continue-on-error: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.os }}-${{ matrix.arch }}
        path: release/
        # 确保即使目录为空也继续
        if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Combine artifacts
      run: |
        mkdir combined-release
        find artifacts -type f -exec cp {} combined-release/ \;

    - name: Check Release Existence
      id: check_release
      uses: actions/github-script@v6
      with:
        script: |
          try {
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ github.ref }}'.replace('refs/tags/', '')
            });
            return true;
          } catch (error) {
            return false;
          }
        result-encoding: string

    - name: Create Release
      id: create_release
      if: steps.check_release.outputs.result == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      continue-on-error: true
      timeout-minutes: 5

    - name: Get Existing Release
      id: get_release
      if: steps.check_release.outputs.result == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const release = await github.rest.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: '${{ github.ref }}'.replace('refs/tags/', '')
          });
          return release.data.upload_url;
        result-encoding: string

    - name: Set Upload URL
      if: steps.check_release.outputs.result == 'true'
      run: |
        echo "upload_url=${{ steps.get_release.outputs.result }}" >> $GITHUB_OUTPUT
      shell: bash
      id: set_upload_url

    - name: Package Artifacts
      run: |
        cd combined-release
        zip -r ../moeCounter-binaries.zip .
        cd ..

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url || steps.set_upload_url.outputs.upload_url }}
        asset_path: ./moeCounter-binaries.zip
        asset_name: moeCounter-binaries.zip
        asset_content_type: application/zip
      continue-on-error: true
      timeout-minutes: 5
